import sys
print >>sys.stderr, 'failing',
sys.exit(1)
